#157045480 Merge gh-pages with master
Davincier/Book-A-Meal pull request #1
Opened 2018-04-24 11:55 UTC by Davincier

Merging the gh-pages with the master to develop and integrate UI pages

2018-04-24 11:57 UTC, Davincier commented
Pull request for UI development

2018-04-24 12:23 UTC, SrMoffat commented
Hey bro,
Good to see you are making progress man! Several things to point out:
a)	Remember to update your README file to be slightly more descriptive than it is
b)	Include a link to your github pages so it can be easy to access the UI and view it
c)	In your order.html, in the table, use a differently colored font because the text is not visible
Keep pushing bro #YOYO

2018-04-24 16:02 UTC, kwahalf requested changes
And your commit messages should follow the best practices

2018-04-24 16:02 UTC, kwahalf commented on README.md
> +https://github.com/Davincier/Book-A-Meal
add screenshots of your app and a description of what your app does, plus explain to a new user who wants  to use your app how to navigate around your app

2018-04-24 16:02 UTC, kwahalf commented
@Davincier  fix the merge conflicts

2018-04-25 10:06 UTC, Davincier commented
#157080994 Merging the gh-pages with the master readme update

2018-04-25 11:44 UTC, merged